# Generated by Django 4.0.2 on 2022-03-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderdetail_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
